CREATE TABLE [dbo].[Roles] (
    [Id]   UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR (256) NOT NULL,
    CONSTRAINT [PK_dbo.Roles] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UC_Roles_Name] UNIQUE NONCLUSTERED ([Name] ASC)
);

