//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOperation
    {
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid OperationId { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Role Role { get; set; }
    }
}
