//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intSoft.Res.ClientSide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientSide {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientSide() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("intSoft.Res.ClientSide.ClientSide", typeof(ClientSide).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ACCEPT_PROFILE {
            get {
                return ResourceManager.GetString("ACCEPT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentoria Administration.
        /// </summary>
        public static string ADMINISTRATION_APPLICATION_NAME_FIND_TEACHER {
            get {
                return ResourceManager.GetString("ADMINISTRATION_APPLICATION_NAME_FIND_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentoria.
        /// </summary>
        public static string APPLICATION_NAME_FIND_TEACHER {
            get {
                return ResourceManager.GetString("APPLICATION_NAME_FIND_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did Somebody Say Tutor?.
        /// </summary>
        public static string APPLICATION_SLOGAN_FIND_TEACHER {
            get {
                return ResourceManager.GetString("APPLICATION_SLOGAN_FIND_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string APPROVED {
            get {
                return ResourceManager.GetString("APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been approved successfully..
        /// </summary>
        public static string APPROVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("APPROVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rate.
        /// </summary>
        public static string AVERAGE_RATE {
            get {
                return ResourceManager.GetString("AVERAGE_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string CHANGE_EMAIL {
            get {
                return ResourceManager.GetString("CHANGE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Phone Number.
        /// </summary>
        public static string CHANGE_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("CHANGE_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DELETED {
            get {
                return ResourceManager.GetString("DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        public static string DELETED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DELETED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to ignore changes?.
        /// </summary>
        public static string DO_YOU_WANT_TO_IGNORE_CHANGES {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_IGNORE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file.
        /// </summary>
        public static string FILE_ERROR {
            get {
                return ResourceManager.GetString("FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this record.
        /// </summary>
        public static string FILE_WILL_NOT_BE_RECOVERABLE {
            get {
                return ResourceManager.GetString("FILE_WILL_NOT_BE_RECOVERABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find A Tutor .
        /// </summary>
        public static string FIND_TUTOR {
            get {
                return ResourceManager.GetString("FIND_TUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha.
        /// </summary>
        public static string INVALID_CAPTCHA {
            get {
                return ResourceManager.GetString("INVALID_CAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha..
        /// </summary>
        public static string INVALIDE_CAPTCHA {
            get {
                return ResourceManager.GetString("INVALIDE_CAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Code.
        /// </summary>
        public static string INVITATION_CODE {
            get {
                return ResourceManager.GetString("INVITATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable this package?.
        /// </summary>
        public static string PACKAGE_DISABLE {
            get {
                return ResourceManager.GetString("PACKAGE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package disabled successfully!.
        /// </summary>
        public static string PACKAGE_DISABLED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PACKAGE_DISABLED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable this package?.
        /// </summary>
        public static string PACKAGE_ENABLE {
            get {
                return ResourceManager.GetString("PACKAGE_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package enabled successfully!.
        /// </summary>
        public static string PACKAGE_ENABLED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PACKAGE_ENABLED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string POINT {
            get {
                return ResourceManager.GetString("POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is accepted.
        /// </summary>
        public static string PROFILE_ACCEPTED {
            get {
                return ResourceManager.GetString("PROFILE_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Not Found.
        /// </summary>
        public static string PROFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("PROFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is not accepted.
        /// </summary>
        public static string PROFILE_REJECTED {
            get {
                return ResourceManager.GetString("PROFILE_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string REJECT_PROFILE {
            get {
                return ResourceManager.GetString("REJECT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review has been added successfuly.
        /// </summary>
        public static string REVIEW_ADDED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("REVIEW_ADDED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully..
        /// </summary>
        public static string SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string SELECT_DAY {
            get {
                return ResourceManager.GetString("SELECT_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string SELECT_MONTH {
            get {
                return ResourceManager.GetString("SELECT_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string SELECT_YEAR {
            get {
                return ResourceManager.GetString("SELECT_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution in Mentoria, the degree will be reviewed by the administrator to be approved, and you will be informed when it is available..
        /// </summary>
        public static string SUCCESS_WHEN_USER_ADD_DEGREE {
            get {
                return ResourceManager.GetString("SUCCESS_WHEN_USER_ADD_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution in Mentoria, the language will be reviewed by the administrator to be approved, and you will be informed when it is available..
        /// </summary>
        public static string SUCCESS_WHEN_USER_ADD_LANGUAGE {
            get {
                return ResourceManager.GetString("SUCCESS_WHEN_USER_ADD_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution in Mentoria, the city will be reviewed by the administrator to be approved, and you will be informed when it is available..
        /// </summary>
        public static string SUCCESS_WHEN_USER_ADD_LOCATION {
            get {
                return ResourceManager.GetString("SUCCESS_WHEN_USER_ADD_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution in Mentoria, the qualification will be reviewed by the administrator to be approved, and you will be informed when it is available..
        /// </summary>
        public static string SUCCESS_WHEN_USER_ADD_QUALIFICATION {
            get {
                return ResourceManager.GetString("SUCCESS_WHEN_USER_ADD_QUALIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution in Mentoria, the subject will be reviewed by the administrator to be approved, and you will be informed when it is available..
        /// </summary>
        public static string SUCCESS_WHEN_USER_ADD_SUBJECT {
            get {
                return ResourceManager.GetString("SUCCESS_WHEN_USER_ADD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Reviews.
        /// </summary>
        public static string TOTAL_NUMBER_OF_REVIEWS {
            get {
                return ResourceManager.GetString("TOTAL_NUMBER_OF_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Views.
        /// </summary>
        public static string TOTAL_VIEWS {
            get {
                return ResourceManager.GetString("TOTAL_VIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile picture.
        /// </summary>
        public static string UPDATE_POFILE_PICTURE {
            get {
                return ResourceManager.GetString("UPDATE_POFILE_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Entity can&apos;t be deleted.
        /// </summary>
        public static string UsedEntityCantBeDeleted {
            get {
                return ResourceManager.GetString("UsedEntityCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification email was sent to your inbox, please verify your email..
        /// </summary>
        public static string VERIFICATION_EMAIL_SENT_MESSAGE {
            get {
                return ResourceManager.GetString("VERIFICATION_EMAIL_SENT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string VIEW_PROFILE {
            get {
                return ResourceManager.GetString("VIEW_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yow will approve the record..
        /// </summary>
        public static string YOU_WILL_APPROVE_THE_RECORD {
            get {
                return ResourceManager.GetString("YOU_WILL_APPROVE_THE_RECORD", resourceCulture);
            }
        }
    }
}
