//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intSoft.Res.DisplayNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("intSoft.Res.DisplayNames.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we wanted to add Nasr City, for example, we would select Cairo as the governorate to which Nasr city belongs, then we would type (مدينة نصر) in The Name Field and (Nasr City) in the Latin Name Field..
        /// </summary>
        public static string AddNewCityLegend {
            get {
                return ResourceManager.GetString("AddNewCityLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new city.
        /// </summary>
        public static string AddNewCityTitle {
            get {
                return ResourceManager.GetString("AddNewCityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we wanted to add Software Engineering as a qualification, we would type (هندسة البرمجيات) in the Name Field and (Software Engineering) in the Latin Name Field..
        /// </summary>
        public static string AddNewQualificationLegend {
            get {
                return ResourceManager.GetString("AddNewQualificationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new qualification.
        /// </summary>
        public static string AddNewQualificationTitle {
            get {
                return ResourceManager.GetString("AddNewQualificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we wanted to add Math subject, for example, we would type (رياضيات) in the Name Field and (Math) in the Latin Name Field..
        /// </summary>
        public static string AddNewSubjectLegend {
            get {
                return ResourceManager.GetString("AddNewSubjectLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new subject.
        /// </summary>
        public static string AddNewSubjectTitle {
            get {
                return ResourceManager.GetString("AddNewSubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cities.
        /// </summary>
        public static string AllCities {
            get {
                return ResourceManager.GetString("AllCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects available.
        /// </summary>
        public static string AllSubjects {
            get {
                return ResourceManager.GetString("AllSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string AnErrorOccurredWhileProcessingRequest {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply now, introduce yourself to learners, advertise your qualification to make money and increase your income.
        /// </summary>
        public static string ApplyDescription {
            get {
                return ResourceManager.GetString("ApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY TODAY.
        /// </summary>
        public static string ApplyToday {
            get {
                return ResourceManager.GetString("ApplyToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Mentors.
        /// </summary>
        public static string ApproveMentors {
            get {
                return ResourceManager.GetString("ApproveMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachmentFile {
            get {
                return ResourceManager.GetString("AttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a tutor.
        /// </summary>
        public static string BecomeATutor {
            get {
                return ResourceManager.GetString("BecomeATutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a mentor on Mentoria.
        /// </summary>
        public static string BecomeATutorOnMentoria {
            get {
                return ResourceManager.GetString("BecomeATutorOnMentoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Mentors.
        /// </summary>
        public static string BestMentors {
            get {
                return ResourceManager.GetString("BestMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentors recommended by Mentoria users for high quality and effective educational practices..
        /// </summary>
        public static string BestMentorsDescription {
            get {
                return ResourceManager.GetString("BestMentorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t review yourself!.
        /// </summary>
        public static string Cant_Review_Yourself {
            get {
                return ResourceManager.GetString("Cant_Review_Yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find.
        /// </summary>
        public static string CantFind {
            get {
                return ResourceManager.GetString("CantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find my qualification.
        /// </summary>
        public static string CantFindMyQualification {
            get {
                return ResourceManager.GetString("CantFindMyQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change attachment file.
        /// </summary>
        public static string ChangeAttachmentFile {
            get {
                return ResourceManager.GetString("ChangeAttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        public static string ChangeFileText {
            get {
                return ResourceManager.GetString("ChangeFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of people comments on your profile will be found here..
        /// </summary>
        public static string CommentsByLearnersInYourProfile {
            get {
                return ResourceManager.GetString("CommentsByLearnersInYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare between mentors reviews.
        /// </summary>
        public static string CompareDescription {
            get {
                return ResourceManager.GetString("CompareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Question ?&lt;br /&gt;  We&apos;re here to lend a hand..
        /// </summary>
        public static string ContactHead {
            get {
                return ResourceManager.GetString("ContactHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And here goes the connection information students need to contact you. Make sure you always keep them up to date..
        /// </summary>
        public static string ContactInfoGoesHere {
            get {
                return ResourceManager.GetString("ContactInfoGoesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information misplaced..
        /// </summary>
        public static string ContactInformationInDescription {
            get {
                return ResourceManager.GetString("ContactInformationInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Mentors.
        /// </summary>
        public static string ContactMentors {
            get {
                return ResourceManager.GetString("ContactMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get contact info.
        /// </summary>
        public static string ContactMentorsDescription {
            get {
                return ResourceManager.GetString("ContactMentorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your message and we will reply soon..
        /// </summary>
        public static string ContactUsFormResponse {
            get {
                return ResourceManager.GetString("ContactUsFormResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright @ {0} Mentoria. All rights reserved.
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string DateOfBirthCard {
            get {
                return ResourceManager.GetString("DateOfBirthCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occoured while trying to save the object.
        /// </summary>
        public static string DbErrorOccoured {
            get {
                return ResourceManager.GetString("DbErrorOccoured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe yourself and impress !  Try putting in some information about your experiences and hobbies..
        /// </summary>
        public static string DescribeYourself {
            get {
                return ResourceManager.GetString("DescribeYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience and hobbies.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        public static string DuplicatedEmail {
            get {
                return ResourceManager.GetString("DuplicatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t make this action before confirming your email and phone number..
        /// </summary>
        public static string EmailOrPhoneNotVerified {
            get {
                return ResourceManager.GetString("EmailOrPhoneNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the languages you teach in. Your profile needs at least one language to be visible to hungry students..
        /// </summary>
        public static string EnterAllTheLanguages {
            get {
                return ResourceManager.GetString("EnterAllTheLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Not Found.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while trying to review the teacher.
        /// </summary>
        public static string Error_Occured_while_trying_to_review_the_teacher {
            get {
                return ResourceManager.GetString("Error_Occured_while_trying_to_review_the_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error confirming your email ! please try again later..
        /// </summary>
        public static string ErrorConfirmingEmail {
            get {
                return ResourceManager.GetString("ErrorConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occourd.
        /// </summary>
        public static string ErrorOccourd {
            get {
                return ResourceManager.GetString("ErrorOccourd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occoured while trying to save the object.
        /// </summary>
        public static string ErrorOccouredWhileTryingToSaveData {
            get {
                return ResourceManager.GetString("ErrorOccouredWhileTryingToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the cities you are willing to teach in. Your profile needs at least one location to be visible to hungry students..
        /// </summary>
        public static string FillInTheCities {
            get {
                return ResourceManager.GetString("FillInTheCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a mentor.
        /// </summary>
        public static string FindAMentor {
            get {
                return ResourceManager.GetString("FindAMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find mentors.
        /// </summary>
        public static string FindMentors {
            get {
                return ResourceManager.GetString("FindMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find mentors in easy steps.
        /// </summary>
        public static string FindMentorsDescription {
            get {
                return ResourceManager.GetString("FindMentorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string FooterLanguages {
            get {
                return ResourceManager.GetString("FooterLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the place where you introduce yourself to the world. Click next to start setting up your profile..
        /// </summary>
        public static string HereYouIntroduceYourself {
            get {
                return ResourceManager.GetString("HereYouIntroduceYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can we help you ? (1000 character).
        /// </summary>
        public static string HowCanWeHelpYou {
            get {
                return ResourceManager.GetString("HowCanWeHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate profile picture..
        /// </summary>
        public static string InappropriateProfileImage {
            get {
                return ResourceManager.GetString("InappropriateProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invitation Code.
        /// </summary>
        public static string InvalidInvitationCode {
            get {
                return ResourceManager.GetString("InvalidInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password (password must be at least 6 characters and contain one digit, one lowercase character, 1 uppercae character and one special character ).
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalide verification code!.
        /// </summary>
        public static string InvalidPhoneVerificationCode {
            get {
                return ResourceManager.GetString("InvalidPhoneVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Code.
        /// </summary>
        public static string InvitationCode {
            get {
                return ResourceManager.GetString("InvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Email Confirmed.
        /// </summary>
        public static string IsEmailConfirmed {
            get {
                return ResourceManager.GetString("IsEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Legend.
        /// </summary>
        public static string LanguageLegend {
            get {
                return ResourceManager.GetString("LanguageLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Name.
        /// </summary>
        public static string LatinName {
            get {
                return ResourceManager.GetString("LatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin name is already Exist.
        /// </summary>
        public static string LatinNameExist {
            get {
                return ResourceManager.GetString("LatinNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list with all your qualifications will always be a plus ;).
        /// </summary>
        public static string ListAllUrQualification {
            get {
                return ResourceManager.GetString("ListAllUrQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Parent.
        /// </summary>
        public static string LocationParent {
            get {
                return ResourceManager.GetString("LocationParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed file size is {0} MB.
        /// </summary>
        public static string MaxSizeExceed {
            get {
                return ResourceManager.GetString("MaxSizeExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet your profile.
        /// </summary>
        public static string MeetYourProfile {
            get {
                return ResourceManager.GetString("MeetYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor.
        /// </summary>
        public static string Mentor {
            get {
                return ResourceManager.GetString("Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor name.
        /// </summary>
        public static string MentorName {
            get {
                return ResourceManager.GetString("MentorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply now, introduce yourself to learners, advertise your qualification to make money and increase your income.
        /// </summary>
        public static string MentorRegistrationLegend {
            get {
                return ResourceManager.GetString("MentorRegistrationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a mentor.
        /// </summary>
        public static string MentorRegistrationTitle {
            get {
                return ResourceManager.GetString("MentorRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentors need to be approved....
        /// </summary>
        public static string MentorsNeedToBeApproved {
            get {
                return ResourceManager.GetString("MentorsNeedToBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most demanded mentors.
        /// </summary>
        public static string MostDemandedMentors {
            get {
                return ResourceManager.GetString("MostDemandedMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mentors in {1}.
        /// </summary>
        public static string MostDemandedMentorsTemplate {
            get {
                return ResourceManager.GetString("MostDemandedMentorsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New phone number.
        /// </summary>
        public static string NewPhoneNumber {
            get {
                return ResourceManager.GetString("NewPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string NewRmail {
            get {
                return ResourceManager.GetString("NewRmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages added.
        /// </summary>
        public static string NoLanguagesAdded {
            get {
                return ResourceManager.GetString("NoLanguagesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language was specified..
        /// </summary>
        public static string NoLanguageSpecified {
            get {
                return ResourceManager.GetString("NoLanguageSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations added.
        /// </summary>
        public static string NoLocationsAdded {
            get {
                return ResourceManager.GetString("NoLocationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location was specified..
        /// </summary>
        public static string NoLocationSpecified {
            get {
                return ResourceManager.GetString("NoLocationSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subjects added.
        /// </summary>
        public static string NoSubjectsAdded {
            get {
                return ResourceManager.GetString("NoSubjectsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject was specified..
        /// </summary>
        public static string NoSubjectSpecified {
            get {
                return ResourceManager.GetString("NoSubjectSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accepted file, the accepted file extensions are {0}..
        /// </summary>
        public static string NotAcceptedFile {
            get {
                return ResourceManager.GetString("NotAcceptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not rated yet!.
        /// </summary>
        public static string NotRatedYet {
            get {
                return ResourceManager.GetString("NotRatedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reviewed.
        /// </summary>
        public static string NotReviewed {
            get {
                return ResourceManager.GetString("NotReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Operations.
        /// </summary>
        public static string NumberOfOperations {
            get {
                return ResourceManager.GetString("NumberOfOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Users.
        /// </summary>
        public static string NumberOfUsers {
            get {
                return ResourceManager.GetString("NumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkEvaluation {
            get {
                return ResourceManager.GetString("OkEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our company.
        /// </summary>
        public static string OurCompany {
            get {
                return ResourceManager.GetString("OurCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mentors.
        /// </summary>
        public static string OurMentors {
            get {
                return ResourceManager.GetString("OurMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm do not match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone not confirmed.
        /// </summary>
        public static string PhoneNotConfirmed {
            get {
                return ResourceManager.GetString("PhoneNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Verification.
        /// </summary>
        public static string PhoneVerification {
            get {
                return ResourceManager.GetString("PhoneVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code you recieved on your phone.
        /// </summary>
        public static string PhoneVerificationNumberLabel {
            get {
                return ResourceManager.GetString("PhoneVerificationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Digits code.
        /// </summary>
        public static string PhoneVerificationNumberPlaceHolder {
            get {
                return ResourceManager.GetString("PhoneVerificationNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Points.
        /// </summary>
        public static string PointsAmount {
            get {
                return ResourceManager.GetString("PointsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Hour.
        /// </summary>
        public static string PricePerHour {
            get {
                return ResourceManager.GetString("PricePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per hour:.
        /// </summary>
        public static string PricePerhourCard {
            get {
                return ResourceManager.GetString("PricePerhourCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your basic information goes here..
        /// </summary>
        public static string PutUrGeneralInfo {
            get {
                return ResourceManager.GetString("PutUrGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} degree in {1}, from {2}.
        /// </summary>
        public static string QualificationNameTemplate {
            get {
                return ResourceManager.GetString("QualificationNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate must be specified.
        /// </summary>
        public static string RateMustBeSpecified {
            get {
                return ResourceManager.GetString("RateMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate.
        /// </summary>
        public static string Reactivate {
            get {
                return ResourceManager.GetString("Reactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register As.
        /// </summary>
        public static string RegisterAs {
            get {
                return ResourceManager.GetString("RegisterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection reasons list.
        /// </summary>
        public static string RejectionList {
            get {
                return ResourceManager.GetString("RejectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the candidate reasons behind the rejection..
        /// </summary>
        public static string RejectionListLegend {
            get {
                return ResourceManager.GetString("RejectionListLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn\&apos;t recieve the code? You can resend the verification code after.
        /// </summary>
        public static string ResendPhoneVerificationCodeMessage {
            get {
                return ResourceManager.GetString("ResendPhoneVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Information.
        /// </summary>
        public static string RoleInformation {
            get {
                return ResourceManager.GetString("RoleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by mentor name.
        /// </summary>
        public static string SearchByMentorName {
            get {
                return ResourceManager.GetString("SearchByMentorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an attachment file.
        /// </summary>
        public static string SelectAttachmentFile {
            get {
                return ResourceManager.GetString("SelectAttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all cities.
        /// </summary>
        public static string SelectCities {
            get {
                return ResourceManager.GetString("SelectCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select degrees.
        /// </summary>
        public static string SelectDegrees {
            get {
                return ResourceManager.GetString("SelectDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectFileText {
            get {
                return ResourceManager.GetString("SelectFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose gender.
        /// </summary>
        public static string SelectGenderType {
            get {
                return ResourceManager.GetString("SelectGenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select governorate.
        /// </summary>
        public static string SelectGovernorate {
            get {
                return ResourceManager.GetString("SelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Institution.
        /// </summary>
        public static string SelectInstitution {
            get {
                return ResourceManager.GetString("SelectInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all languages.
        /// </summary>
        public static string SelectLanguages {
            get {
                return ResourceManager.GetString("SelectLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location type.
        /// </summary>
        public static string SelectLocationType {
            get {
                return ResourceManager.GetString("SelectLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select qualifications.
        /// </summary>
        public static string SelectQualifications {
            get {
                return ResourceManager.GetString("SelectQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select subject.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all subjects.
        /// </summary>
        public static string SelectSubjects {
            get {
                return ResourceManager.GetString("SelectSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your profile picture here..
        /// </summary>
        public static string SetUrProfilePicture {
            get {
                return ResourceManager.GetString("SetUrProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration.
        /// </summary>
        public static string StudentRegistration {
            get {
                return ResourceManager.GetString("StudentRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a mentor.
        /// </summary>
        public static string StudentRegistrationLegend {
            get {
                return ResourceManager.GetString("StudentRegistrationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of all the subjects are.
        /// </summary>
        public static string SubjectLegend {
            get {
                return ResourceManager.GetString("SubjectLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects you teach and master. Your profile needs at least one subject to be visible to students..
        /// </summary>
        public static string SubjectsYouTeach {
            get {
                return ResourceManager.GetString("SubjectsYouTeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Reviwed successfully.
        /// </summary>
        public static string Teacher_Reviwed_successfully {
            get {
                return ResourceManager.GetString("Teacher_Reviwed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Registration.
        /// </summary>
        public static string TeacherRegistration {
            get {
                return ResourceManager.GetString("TeacherRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of services.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible.
        /// </summary>
        public static string Terrible {
            get {
                return ResourceManager.GetString("Terrible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string ThisAccountLocked {
            get {
                return ResourceManager.GetString("ThisAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Subjects.
        /// </summary>
        public static string TrendingSubjects {
            get {
                return ResourceManager.GetString("TrendingSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have mentors in different subjects over different cities. Here&apos;s what learners are searching for.
        /// </summary>
        public static string TrendingSubjectsDescription {
            get {
                return ResourceManager.GetString("TrendingSubjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the languages in which you can teach the selected subjects.
        /// </summary>
        public static string UserLanguageLegend {
            get {
                return ResourceManager.GetString("UserLanguageLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the cities you are willing to teach in, learners will look you up using these cities.
        /// </summary>
        public static string UserLocationLegend {
            get {
                return ResourceManager.GetString("UserLocationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Master&apos;s degree in software engineering from Cairo University, then choose &quot;Master&quot; in the degree field, &quot;Software Engineering&quot; in the qualification field, and type &quot;Cairo University&quot; in the institution field..
        /// </summary>
        public static string UserQualificationLegend {
            get {
                return ResourceManager.GetString("UserQualificationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the subject you teach and master, learners will look you up using these subjects.
        /// </summary>
        public static string UserSubjectLegend {
            get {
                return ResourceManager.GetString("UserSubjectLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is valid!.
        /// </summary>
        public static string ValidPhoneVerificationCode {
            get {
                return ResourceManager.GetString("ValidPhoneVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contact Information.
        /// </summary>
        public static string ViewContactInformation {
            get {
                return ResourceManager.GetString("ViewContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are always looking for mentors to join our network..
        /// </summary>
        public static string WelookingForMentors {
            get {
                return ResourceManager.GetString("WelookingForMentors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a review....
        /// </summary>
        public static string WriteReviewHint {
            get {
                return ResourceManager.GetString("WriteReviewHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceed the maximun length.
        /// </summary>
        public static string YouHaveExceedTheMaximunLength {
            get {
                return ResourceManager.GetString("YouHaveExceedTheMaximunLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is offline until you fix these points.
        /// </summary>
        public static string YourProfileIsOfflineUntil {
            get {
                return ResourceManager.GetString("YourProfileIsOfflineUntil", resourceCulture);
            }
        }
    }
}
