//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intSoft.Res.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("intSoft.Res.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email by clicking &lt;a href=&apos;{0}&apos;&gt;here.&lt;/a&gt;.
        /// </summary>
        public static string ActivationEmailBody {
            get {
                return ResourceManager.GetString("ActivationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Email.
        /// </summary>
        public static string ActivationEmailTitle {
            get {
                return ResourceManager.GetString("ActivationEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiForgery Token Cookie Not Found.
        /// </summary>
        public static string AntiForgeryTokenCookieNotFound {
            get {
                return ResourceManager.GetString("AntiForgeryTokenCookieNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one reason should be selected or note should be filled.
        /// </summary>
        public static string AtLeastOneReasonOrNoteShouldBeSelected {
            get {
                return ResourceManager.GetString("AtLeastOneReasonOrNoteShouldBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email was sent to your inbox.
        /// </summary>
        public static string ConfirmResetMessage {
            get {
                return ResourceManager.GetString("ConfirmResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily contact information request limit was exceeded.
        /// </summary>
        public static string ContactViewLimitExceeded {
            get {
                return ResourceManager.GetString("ContactViewLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact information was viewed.
        /// </summary>
        public static string ContactViewNotificationMessage {
            get {
                return ResourceManager.GetString("ContactViewNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email was changed successfully! Check your inbox to confirm your new email.
        /// </summary>
        public static string EmailChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is confirmed!.
        /// </summary>
        public static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin name is already exist, however, if you can&apos;t find it in the list then it is waiting for the administration&apos;s approval..
        /// </summary>
        public static string LatinNameExist {
            get {
                return ResourceManager.GetString("LatinNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) city, you have suggested recently, is available online now.
        /// </summary>
        public static string LocationApproveNotificationMessage {
            get {
                return ResourceManager.GetString("LocationApproveNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already exist, however, if you can&apos;t find it in the list then it is waiting for the administration&apos;s approval..
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data that matches your filters, please try again with different filters..
        /// </summary>
        public static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not authorized..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully!.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was changed successfully!.
        /// </summary>
        public static string PhoneNumberChangedSuccessfully {
            get {
                return ResourceManager.GetString("PhoneNumberChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new phone number is confirmed now!.
        /// </summary>
        public static string PhoneNumberConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been activated !.
        /// </summary>
        public static string ProfileActivatedNotificationMessage {
            get {
                return ResourceManager.GetString("ProfileActivatedNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been rejected !
        ///Click for more information.
        /// </summary>
        public static string ProfileDisabledNotificationMessage {
            get {
                return ResourceManager.GetString("ProfileDisabledNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Not Found.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new review was posted to your profile.
        /// </summary>
        public static string ProfileReviewNotificationMessage {
            get {
                return ResourceManager.GetString("ProfileReviewNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new profile visit.
        /// </summary>
        public static string ProfileViewNotificationMessage {
            get {
                return ResourceManager.GetString("ProfileViewNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) qualification, you have suggested recently, is available online now.
        /// </summary>
        public static string QualificationApproveNotificationMessage {
            get {
                return ResourceManager.GetString("QualificationApproveNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile is rejected now, and the rejection E-mail was sent..
        /// </summary>
        public static string RejectionEmailSent {
            get {
                return ResourceManager.GetString("RejectionEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Mail.
        /// </summary>
        public static string RejectionMailSubject {
            get {
                return ResourceManager.GetString("RejectionMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review on ({0}) profile has been approved..
        /// </summary>
        public static string ReviewApproved {
            get {
                return ResourceManager.GetString("ReviewApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review on ({0}) profile has been rejected, please read Mentoria&apos;s review rules..
        /// </summary>
        public static string ReviewRejected {
            get {
                return ResourceManager.GetString("ReviewRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews need to be approved.
        /// </summary>
        public static string ReviewsNeedToBeAproved {
            get {
                return ResourceManager.GetString("ReviewsNeedToBeAproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your contribution, The review will be available online if it dosen&apos;t violet any of Menotria&apos;s review rules..
        /// </summary>
        public static string ReviewToBeApprovedMessage {
            get {
                return ResourceManager.GetString("ReviewToBeApprovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) subject, you have suggested recently, is available online now.
        /// </summary>
        public static string SubjectApproveNotificationMessage {
            get {
                return ResourceManager.GetString("SubjectApproveNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert duplicate key row in table with unique constraint.
        /// </summary>
        public static string UniqueConstraintViolation {
            get {
                return ResourceManager.GetString("UniqueConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert duplicate key row in table with unique index.
        /// </summary>
        public static string UniqueIndexViolation {
            get {
                return ResourceManager.GetString("UniqueIndexViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnKnown error has occurred.
        /// </summary>
        public static string UnKnownErrorHasOccurred {
            get {
                return ResourceManager.GetString("UnKnownErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Entity Can&apos;t Be Deleted..
        /// </summary>
        public static string UsedEntityCantBeDeleted {
            get {
                return ResourceManager.GetString("UsedEntityCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t review the same teacher twice.
        /// </summary>
        public static string UserCantReviewTheSameTeacherTwice {
            get {
                return ResourceManager.GetString("UserCantReviewTheSameTeacherTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add the same language twice.
        /// </summary>
        public static string YouCantAddTheSameLanguageTwice {
            get {
                return ResourceManager.GetString("YouCantAddTheSameLanguageTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add the same location twice.
        /// </summary>
        public static string YouCantAddTheSameLocationTwice {
            get {
                return ResourceManager.GetString("YouCantAddTheSameLocationTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add the same role twice.
        /// </summary>
        public static string YouCantAddTheSameRoleTwice {
            get {
                return ResourceManager.GetString("YouCantAddTheSameRoleTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add the same subject twice.
        /// </summary>
        public static string YouCantAddTheSameSubjectTwice {
            get {
                return ResourceManager.GetString("YouCantAddTheSameSubjectTwice", resourceCulture);
            }
        }
    }
}
